backend:
  name: gitlab
  branch: master
  repo: hasonm/tradice.net
  base_url: https://gitlab.com/oauth/authorize?client_id=d7f2983ad34980a6b4370c0c1d8a22f8c1798a7acc9dcb2203a240199533cecd&redirect_uri=http://localhost:8080&response_type=token

display_url: https://tradice.net
media_folder: static/images/post

collections: # A list of collections the CMS should be able to edit
  - name: "posts"
    label: "Příspěvky"
    description: >
      Příspěvky
    folder: "content/post"
    slug: "{{year}}-{{month}}-{{day}}"
    create: true
    fields:
      - {label: "Titulek", name: "title", widget: "string", tagname: "h1"}
      - {label: "Datum", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Obrázek", name: "thumbnail", widget: "image", required: false, tagname: ""}
      - label: "Štítky"
        name: tags
        required: false,
        widget: list
        default: []
      - {label: "Text", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Stránky"
    folder: "content/page"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titulek", name: "title", widget: "string", tagname: "h1"}
      - {label: "Titulek odkazu", name: "linktitle", widget: "string"}
      - {label: "Šablona", name: "layout", required: false, widget: "string"}
#      - label: "Menu"
#        name: "menu"
#        widget: "object"
      - {label: "Text", name: "body", widget: "markdown"}

